
import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';
import { Language } from '../types.ts';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  English: {
    nav_home: 'Home',
    nav_query: 'AI Query',
    nav_live: 'Voice Advisory',
    nav_community: 'Community',
    nav_schemes: 'Govt Schemes',
    nav_profile: 'My Profile',
    nav_dashboard: 'Officer Dashboard',
    nav_tech: 'Technical Details',
    nav_logout: 'Logout',
    nav_store: 'Uzhavan Store',
    nav_weather: 'Weather Hub',
    nav_loans: 'Bank Loans',
    nav_guardian: 'Guardian',
    nav_elam: '🌾 Auction',
    nav_search_placeholder: 'Search crops, products, advice...',
    nav_farmer_role: 'Farmer',
    hero_title_1: 'Uzhavan',
    hero_title_2: 'Forum.',
    hero_subtitle: "Redefining Bharat's agriculture with personalized intelligence. The world's first AI officer for every acre.",
    btn_login: 'Login',
    btn_strategy: 'Strategy',
    home_ai_center: 'AI Agricultural Command Center',
    query_title: 'Farmer Advisory Portal',
    query_diagnostic_title: 'AI Diagnostic Query',
    query_btn_ask: 'Verify with AI Advisory',
    query_analyzing: 'Analyzing Crop Data...',
    query_report_title: 'Advisory Report',
    query_voice_start: 'Listen to Report',
    query_voice_stop: 'Stop Voice',
    query_system_status: 'System Status',
    query_grounding: 'Grounding Status',
    query_optimal: 'Optimal',
    query_voice_ready: 'Ready',
    query_model_series: 'Model Series',
    query_verified_title: 'Verified Diagnosis',
    query_verified_desc: 'Our AI uses real-time satellite data and local soil profiles to verify your crop issues.',
    query_capture_mandatory: 'Upload a crop image or type your question',
    onboarding_title: 'Profile Completion',
    onboarding_choose: 'Choose...',
    onboarding_btn_next: 'Proceed',
    onboarding_btn_complete: 'Complete Setup',
    onboarding_label_land: 'Land Size (Acres)',
    // Crops
    crop_paddy: 'Paddy',
    crop_rubber: 'Rubber',
    crop_coconut: 'Coconut',
    crop_pepper: 'Pepper',
    crop_banana: 'Banana',
    crop_coffee: 'Coffee',
    crop_arecanut: 'Arecanut',
    crop_cardamom: 'Cardamom',
    crop_vegetables: 'Vegetables',
    crop_ginger: 'Ginger',
    crop_turmeric: 'Turmeric',
    // Soil
    soil_black: 'Black Soil',
    soil_red: 'Red Soil',
    soil_alluvial: 'Alluvial Soil',
    soil_laterite: 'Laterite Soil',
    soil_sandy: 'Sandy Soil',
    soil_clay: 'Clay Soil',
    // Irrigation
    irr_drip: 'Drip Irrigation',
    irr_sprinkler: 'Sprinkler',
    irr_canal: 'Canal Irrigation',
    irr_well: 'Well / Borewell',
    irr_rain: 'Rain-fed',
    // Weather
    weather_title: 'Weather Hub',
    weather_feed_title: 'Live Atmospheric Feed.',
    weather_recent: 'Recent Locations',
    weather_scanning: 'Scanning Atmosphere...',
    weather_system_suitability_ai: 'System Suitability AI',
    weather_verify_now: 'Verify Now',
    weather_weekly: 'Weekly Forecast',
    weather_advisory_title: 'AI Advisory',
    weather_log: 'Planting History Log',
    weather_spec: 'Specification',
    weather_verdict: 'AI Verdict',
    weather_matrix: 'Scientific Matrix',
    weather_logic: 'Advisory Logic',
    weather_hear_analysis: 'Hear Analysis',
    weather_km_h: 'km/h',
    weather_humidity: 'Humidity',
    weather_btn_fetch: 'Fetch Feed',
    // WMO Codes
    wmo_0: 'Clear Sky',
    wmo_1: 'Mainly Clear',
    wmo_2: 'Partly Cloudy',
    wmo_3: 'Overcast',
    wmo_45: 'Foggy',
    wmo_48: 'Rime Fog',
    wmo_51: 'Light Drizzle',
    wmo_53: 'Moderate Drizzle',
    wmo_55: 'Dense Drizzle',
    wmo_61: 'Slight Rain',
    wmo_63: 'Moderate Rain',
    wmo_65: 'Heavy Rain',
    wmo_80: 'Slight Showers',
    wmo_81: 'Moderate Showers',
    wmo_82: 'Violent Showers',
    wmo_95: 'Thunderstorm',
    // Schemes
    schemes_title: 'Govt Schemes',
    schemes_discovery: 'Discovery',
    schemes_subtitle: 'Access verified central and state agriculture benefits active through 2026.',
    schemes_central: 'Central',
    schemes_state: 'State',
    schemes_verified: 'Verified 2026',
    schemes_proceed_portal: 'Proceed to Official Portal',
    scheme_pmkisan_name: 'PM-KISAN (Income Support)',
    scheme_pmkisan_desc: 'Direct income support of ₹6,000 per year to all landholding farmer families.',
    scheme_pmfby_name: 'PMFBY (Crop Insurance)',
    scheme_pmfby_desc: 'Yield-based crop insurance against non-preventable natural risks.',
    scheme_kcc_name: 'Kisan Credit Card (KCC)',
    scheme_kcc_desc: 'Credit support for crop production, maintenance, and consumption needs.',
    scheme_shc_name: 'Soil Health Card Scheme',
    scheme_shc_desc: 'Scientific analysis of soil health to suggest suitable nutrients and fertilizers.',
    scheme_pkvy_name: 'Paramparagat Krishi Vikas Yojana',
    scheme_pkvy_desc: 'Supporting and promoting organic farming through cluster approach.',
    scheme_nmsa_name: 'Mission for Sustainable Agriculture',
    scheme_nmsa_desc: 'Enhancing agricultural productivity focusing on integrated farming and water efficiency.',
    scheme_pmksy_name: 'PM Krishi Sinchayee Yojana',
    scheme_pmksy_desc: 'Har Khet Ko Pani - Providing end-to-end solutions in irrigation supply chain.',
    // Loan Hub / Banks
    loan_hub_title: 'Loan Hub',
    loan_hub_subtitle: 'Real-time agricultural credit discovery grounded by current market data.',
    loan_applied: 'Applied',
    loan_btn_apply: 'Apply Now',
    bank_national: 'National Banks',
    bank_state_specific: 'State Cooperative Banks',
    bank_sbi: 'State Bank of India (Agri)',
    bank_nabard: 'NABARD Refinance',
    bank_hdfc: 'HDFC Bank Agri Loans',
    bank_kerala: 'Kerala State Co-operative Bank',
    bank_tnscb: 'Tamil Nadu State Co-operative Bank',
    btn_apply_bank: 'Apply on Bank Portal',
    // Community
    forum_peer_network: 'Krishi Peer-Network',
    forum_title: 'Community Forum',
    forum_btn_post: 'Post Query',
    forum_label_crop: 'Primary Crop',
    forum_label_category: 'Category',
    forum_label_district: 'District',
    forum_label_inquiry: 'Detailed Inquiry',
    forum_btn_submit: 'Submit Query',
    forum_suggestions_title: 'Farmer Peer Suggestions',
    forum_reply_placeholder: 'Type your suggestion...',
    // Live Chat
    live_sync_title: 'Krishi Sync.',
    live_latency: 'Latency',
    live_latency_val: 'Real-time (~200ms)',
    live_engine: 'Core Engine',
    live_engine_val: 'Gemini 2.5 Native',
    live_advisory_mode: 'Voice Mode',
    live_dialect_val: 'English Dialword',
    live_listening: 'Listening...',
    live_idle: 'System Idle',
    live_connecting: 'Establishing Sync...',
    live_you: 'You',
    live_subtitle: 'Real-time voice interaction for instant agricultural support.',
    live_btn_end: 'End',
    live_btn_start: 'Start',
    // Login/Profile
    profile_name_label: 'Registered Full Name',
    profile_age_label: 'Age',
    profile_address_label: 'Farm Address / Location',
    profile_id_label: 'Farmer Registry ID',
    login_title: 'Krishi Login',
    login_subtitle: 'Secure Access Point',
    login_placeholder_phone: 'Phone ID',
    login_placeholder_pass: 'PIN / Password',
    login_btn_enter: 'Enter Command Center',
    login_forgot_pass: 'Forgot Access Code?',
    login_btn_cancel: 'Cancel',
    register_title: 'New Farmer Setup',
    register_subtitle: 'Initialize your Krishi Vault',
    register_btn_secure: 'Secure and Continue',
    footer_desc: 'Empowering farmers with AI-driven agricultural insights for sustainable farming.',
    footer_quick_links: 'Quick Links',
    footer_contact_support: 'Support',
    onboarding_step: 'Step',
    onboarding_completed: 'Completed',
    onboarding_identity_sync: 'Identity Sync',
    onboarding_start_digital_record: 'Start your digital record',
    onboarding_full_name: 'Full Name',
    onboarding_example_name: 'Example: Sachin S',
    onboarding_age: 'Age',
    onboarding_experience: 'Experience (Years)',
    onboarding_farm_address: 'Farm Address',
    onboarding_address_placeholder: 'Village, District, State...',
    onboarding_btn_location: 'Go to Location',
    onboarding_geo_center: 'Geographical Center',
    onboarding_sync_weather: 'Sync with local weather data',
    onboarding_state: 'State',
    onboarding_district: 'District',
    onboarding_select: 'Select...',
    onboarding_btn_back: 'Back',
    onboarding_agri_dna_profile: 'Agricultural DNA Profile',
    onboarding_agri_dna: 'Agricultural DNA',
    onboarding_define_genetics: 'Define your soil and crop genetics',
    onboarding_primary_crop_cultivation: 'Primary Crop Cultivation',
    onboarding_soil_profile: 'Soil Structure Profile',
    onboarding_btn_finalize: 'Finalize Measurements',
    onboarding_operational_status: 'Operational Status',
    onboarding_finalizing_management: 'Finalizing land and resource management',
    onboarding_total_land_size: 'Total Land Size (Acres)',
    onboarding_acres: 'Acres',
    onboarding_irrigation_infrastructure: 'Irrigation Infrastructure',
    onboarding_btn_start_center: 'Start Command Center',
    onboarding_protected_badge: 'Protected by Kisan Identity Protocol',
    guardian_title: 'Uzhavan Smart Irrigation Guardian',
    guardian_tagline: 'Smart Farming Starts Here',
    guardian_buy_now: 'Buy Now',
    guardian_contact_us: 'Contact Us',
    guardian_overview_title: 'Product Overview',
    guardian_overview_desc: 'Our AI-enabled IoT system provides comprehensive monitoring and control for modern agriculture.',
    guardian_soil_moisture: 'Soil Moisture Monitoring',
    guardian_temp_humidity: 'Temperature & Humidity',
    guardian_auto_motor: 'Automatic Motor Control',
    guardian_wifi_realtime: 'WiFi Real-time Monitoring',
    guardian_solar_support: 'Solar Powered Support',
    guardian_features_title: 'Advanced Features',
    guardian_feature_soil: 'Real-time Soil Monitoring',
    guardian_feature_irrigation: 'Smart Irrigation Control',
    guardian_feature_dashboard: 'WiFi Web Dashboard',
    guardian_feature_mobile: 'Mobile Access',
    guardian_feature_energy: 'Energy Efficient',
    guardian_feature_install: 'Easy Installation',
    guardian_how_it_works: 'How It Works',
    guardian_step_1: 'Install device in field',
    guardian_step_2: 'Sensors collect real-time data',
    guardian_step_3: 'ESP32 processes data',
    guardian_step_4: 'Motor auto controls irrigation',
    guardian_step_5: 'Farmer monitors via web dashboard',
    guardian_tech_specs: 'Technical Specifications',
    guardian_spec_mcu: 'Microcontroller: ESP32',
    guardian_spec_soil: 'Soil Sensor: Capacitive Soil Moisture Sensor',
    guardian_spec_env: 'Environmental Sensor: DHT11/DHT22',
    guardian_spec_power: 'Power Supply: 5V / Solar Compatible',
    guardian_spec_wifi: 'Connectivity: WiFi 2.4 GHz',
    guardian_spec_relay: 'Relay Module: 5V Active Low',
    guardian_benefits: 'Benefits',
    guardian_benefit_water: 'Saves Water',
    guardian_benefit_yield: 'Increases Yield',
    guardian_benefit_effort: 'Reduces Manual Effort',
    guardian_benefit_stress: 'Early Stress Detection',
    guardian_benefit_cost: 'Cost Efficient',
    guardian_gallery: 'Image Gallery',
    guardian_pricing: 'Pricing Plans',
    guardian_basic: 'Basic Model',
    guardian_pro: 'Pro Model',
    guardian_enterprise: 'Enterprise Model',
    guardian_cta: 'Upgrade Your Farm Today!',
    // Store
    store_title: 'Uzhavan Store',
    store_badge: 'Farmer\'s Marketplace',
    store_subtitle: 'Premium agricultural products for your farm needs.',
    store_add_cart: 'Add to Cart',
    cat_all: 'All',
    cat_fertilizer: 'Fertilizer',
    cat_pesticide: 'Pesticide',
    cat_seeds: 'Seeds',
    cat_tools: 'Farming Tools',
    // Product Names & Descriptions
    p1_name: 'Neem Oil Pesticide',
    p1_desc: 'Organic cold-pressed neem oil concentrate. Effective against aphids, mites, and fungal infections. 100% natural.',
    p2_name: 'NPK 19:19:19 Fertilizer',
    p2_desc: 'Balanced water-soluble NPK fertilizer for all crops. Promotes healthy root, stem, and fruit development.',
    p3_name: 'Hybrid Paddy Seeds',
    p3_desc: 'High-yield hybrid rice seeds suitable for Tamil Nadu and Kerala climates. Pest-resistant variety, 120-day crop.',
    p4_name: 'Copper Oxychloride Fungicide',
    p4_desc: 'Broad-spectrum copper-based fungicide. Controls downy mildew, leaf spot, and blight in vegetables and paddy.',
    p5_name: 'Vermicompost Organic Manure',
    p5_desc: 'Premium earthworm-processed organic compost. Enriches soil structure, improves water retention and crop quality.',
    p6_name: 'Stainless Steel Sickle',
    p6_desc: 'Traditional curved sickle with razor-sharp stainless steel blade. Ideal for paddy, wheat, and grass harvesting.',
    p7_name: 'Iron Garden Hoe (Kudal)',
    p7_desc: 'Heavy-duty forged iron hoe with ergonomic wooden handle. Perfect for weeding, soil loosening, and bed preparation.',
    p8_name: 'Coconut Tree Climber Kit',
    p8_desc: 'Safe and durable coconut tree climbing aid with anti-slip grip pads. Supports up to 120 kg body weight.',
    p9_name: 'Vegetable Seeds Combo Pack',
    p9_desc: 'Assorted pack of 10 vegetable seed varieties — brinjal, tomato, chilli, beans, bitter gourd, and more.',
    p10_name: 'DAP Fertilizer (50 kg Bag)',
    p10_desc: 'Di-Ammonium Phosphate (DAP) granular fertilizer. Essential for root strengthening and early crop establishment.'
  },
  Malayalam: {
    nav_home: 'ഹോം',
    nav_query: 'AI ചോദ്യങ്ങൾ',
    nav_live: 'വോയ്‌സ് അഡൈ്വസറി',
    nav_community: 'കൂട്ടായ്മ',
    nav_schemes: 'സർക്കാർ പദ്ധതികൾ',
    nav_profile: 'പ്രൊഫൈൽ',
    nav_dashboard: 'ഓഫീസർ ഡാഷ്‌ബോർഡ്',
    nav_tech: 'സാങ്കേതിക വിവരങ്ങൾ',
    nav_logout: 'ലോഗൗട്ട്',
    nav_store: 'കൃഷി സ്റ്റോർ',
    nav_weather: 'കാലാവസ്ഥ',
    nav_loans: 'ബാങ്ക് ലോണുകൾ',
    nav_guardian: 'ഗാർഡിയൻ',
    nav_elam: '🌾 ലേലം',
    nav_search_placeholder: 'തിരയുക...',
    nav_farmer_role: 'കർഷകൻ',
    hero_title_1: 'ഉഴവൻ',
    hero_title_2: 'ഫോറം.',
    hero_subtitle: "വ്യക്തിഗതമാക്കിയ ഇന്റലിജൻസിലൂടെ ഭാരതത്തിന്റെ കൃഷി പുനർനിർവചിക്കുന്നു.",
    btn_login: 'ലോഗിൻ',
    btn_strategy: 'തന്ത്രം',
    home_ai_center: 'AI കാർഷിക കമാൻഡ് സെന്റർ',
    query_title: 'കർഷക ഉപദേശക പോർട്ടൽ',
    query_diagnostic_title: 'AI ഡയഗ്നോസ്റ്റിക് ക്വറി',
    query_btn_ask: 'AI ഉപദേശം തേടുക',
    query_analyzing: 'വിവരങ്ങൾ വിശകലനം ചെയ്യുന്നു...',
    query_report_title: 'റിപ്പോർട്ട്',
    query_voice_start: 'ശബ്ദം കേൾക്കുക',
    query_voice_stop: 'നിർത്തുക',
    query_system_status: 'സിസ്റ്റം സ്റ്റാറ്റസ്',
    query_grounding: 'ഗ്രൗണ്ടിംഗ് സ്റ്റാറ്റസ്',
    query_optimal: 'ഒപ്റ്റിമൽ',
    query_voice_ready: 'റെഡി',
    query_model_series: 'മോഡൽ സീരീസ്',
    query_verified_title: 'സ്ഥിരീകരിച്ച റിപ്പോർട്ട്',
    query_verified_desc: 'ഞങ്ങളുടെ AI സാറ്റലൈറ്റ് ഡാറ്റ ഉപയോഗിച്ച് നിങ്ങളുടെ വിള പ്രശ്നങ്ങൾ പരിശോധിക്കുന്നു.',
    query_capture_mandatory: 'ഒരു ചിത്രം അപ്‌ലോഡ് ചെയ്യുക അല്ലെങ്കിൽ ചോദ്യം ടൈപ്പ് ചെയ്യുക',
    onboarding_title: 'പ്രൊഫൈൽ പൂർത്തിയാക്കൽ',
    onboarding_choose: 'തിരഞ്ഞെടുക്കുക...',
    onboarding_btn_next: 'തുടരുക',
    onboarding_btn_complete: 'പൂർത്തിയാക്കുക',
    onboarding_label_land: 'ഭൂമിയുടെ അളവ് (ഏക്കർ)',
    crop_paddy: 'നെല്ല്',
    crop_rubber: 'റബ്ബർ',
    crop_coconut: 'തെങ്ങ്',
    crop_pepper: 'കുരുമുളക്',
    crop_banana: 'വാഴ',
    crop_coffee: 'കാപ്പി',
    crop_arecanut: 'കവുങ്ങ്',
    crop_cardamom: 'ഏലം',
    crop_vegetables: 'പച്ചക്കറികൾ',
    crop_ginger: 'ഇഞ്ചി',
    crop_turmeric: 'മഞ്ഞൾ',
    soil_black: 'കറുത്ത മണ്ണ്',
    soil_red: 'ചുവന്ന മണ്ണ്',
    soil_alluvial: 'എക്കൽ മണ്ണ്',
    soil_laterite: 'ലാറ്ററൈറ്റ് മണ്ണ്',
    soil_sandy: 'മണൽ മണ്ണ്',
    soil_clay: 'കളിമണ്ണ്',
    irr_drip: 'തുള്ളിനന',
    irr_sprinkler: 'സ്പ്രിംഗ്ലർ',
    irr_canal: 'കനാൽ നന',
    irr_well: 'കിണർ / ബോർവെൽ',
    irr_rain: 'മഴയെ ആശ്രയിച്ചുള്ള കൃഷി',
    weather_title: 'കാലാവസ്ഥ',
    weather_feed_title: 'തത്സമയ കാലാവസ്ഥാ വിവരം.',
    weather_recent: 'സമീപകാല സ്ഥലങ്ങൾ',
    weather_scanning: 'അന്തരീക്ഷം നിരീക്ഷിക്കുന്നു...',
    weather_system_suitability_ai: 'കൃഷി അനുയോജ്യത AI',
    weather_verify_now: 'പരിശോധിക്കുക',
    weather_weekly: 'വാരാന്ത പ്രവചനം',
    weather_advisory_title: 'AI ഉപദേശം',
    weather_log: 'കൃഷി ചരിത്രം',
    weather_spec: 'വിശദാംശങ്ങൾ',
    weather_verdict: 'AI തീരുമാനം',
    weather_matrix: 'ശാസ്ത്രീയ വിശകലനം',
    weather_logic: 'ഉപദേശ യുക്തി',
    weather_hear_analysis: 'വിശകലനം കേൾക്കുക',
    weather_km_h: 'കി.മീ/മണിക്കൂർ',
    weather_humidity: 'ഈർപ്പം',
    weather_btn_fetch: 'അപ്‌ഡേറ്റ് ചെയ്യുക',
    wmo_0: 'തെളിഞ്ഞ ആകാശം',
    wmo_1: 'പ്രധാനമായും തെളിഞ്ഞത്',
    wmo_2: 'ഭാഗികമായി മേഘാവൃതം',
    wmo_3: 'മേഘാവൃതം',
    wmo_45: 'മഞ്ഞ്',
    wmo_48: 'കനത്ത മഞ്ഞ്',
    wmo_51: 'നേരിയ മഴ',
    wmo_53: 'മിതമായ മഴ',
    wmo_55: 'കനത്ത മഴ',
    wmo_61: 'നേരിയ തോതിൽ മഴ',
    wmo_63: 'മിതമായ തോതിൽ മഴ',
    wmo_65: 'ശക്തമായ മഴ',
    wmo_80: 'മഴത്തുള്ളികൾ',
    wmo_81: 'മിതമായ മഴത്തുള്ളികൾ',
    wmo_82: 'ശക്തമായ മഴത്തുള്ളികൾ',
    wmo_95: 'ഇടിമിന്നലോടു കൂടിയ മഴ',
    // Schemes ML
    schemes_title: 'സർക്കാർ പദ്ധതികൾ',
    schemes_discovery: 'തിരയുക',
    schemes_subtitle: '2026 വരെ ലഭ്യമായ കേന്ദ്ര-സംസ്ഥാന കാർഷിക ആനുകൂല്യങ്ങൾ.',
    schemes_central: 'കേന്ദ്രം',
    schemes_state: 'സംസ്ഥാനം',
    schemes_verified: 'സ്ഥിരീകരിച്ചത് 2026',
    schemes_proceed_portal: 'പോർട്ടലിലേക്ക് പോകുക',
    scheme_pmkisan_name: 'PM-KISAN (വരുമാന സഹായം)',
    scheme_pmkisan_desc: 'എല്ലാ കർഷക കുടുംബങ്ങൾക്കും വർഷം ₹6,000 വരുമാന സഹായം.',
    scheme_pmfby_name: 'PMFBY (വിള ഇൻഷുറൻസ്)',
    scheme_pmfby_desc: 'പ്രകൃതിക്ഷോഭങ്ങൾക്കെതിരെയുള്ള വിള ഇൻഷുറൻസ്.',
    scheme_kcc_name: 'കിസാൻ ക്രെഡിറ്റ് കാർഡ് (KCC)',
    scheme_kcc_desc: 'കൃഷിക്കാവശ്യമായ ഹ്രസ്വകാല വായ്പകൾ നൽകുന്ന പദ്ധതി.',
    scheme_shc_name: 'സോയിൽ ഹെൽത്ത് കാർഡ്',
    scheme_shc_desc: 'മണ്ണിലെ പോഷകാംശങ്ങൾ പരിശോധിച്ച് റിപ്പോർട്ട് നൽകുന്ന പദ്ധതി.',
    scheme_pkvy_name: 'പരമ്പരാഗത കൃഷി വികാസ് യോജന',
    scheme_pkvy_desc: 'ജൈവകൃഷിയെ പ്രോത്സാഹിപ്പിക്കുന്നതിനുള്ള പദ്ധതി.',
    scheme_nmsa_name: 'സുസ്ഥിര കൃഷി മിഷൻ',
    scheme_nmsa_desc: 'സംയോജിത കൃഷിയിലൂടെ ഉൽപ്പാദനക്ഷമത വർദ്ധിപ്പിക്കുന്നു.',
    scheme_pmksy_name: 'PM കൃഷി സിഞ്ചായീ യോജന',
    scheme_pmksy_desc: 'എല്ലാ കൃഷിയിടങ്ങളിലേക്കും ജലസേചനം ഉറപ്പാക്കുന്നു.',
    // Loan Hub ML
    loan_hub_title: 'ലോൺ ഹബ്',
    loan_hub_subtitle: 'കർഷകർക്കുള്ള വായ്പാ വിവരങ്ങൾ തത്സമയം അറിയുക.',
    loan_applied: 'അപേക്ഷിച്ചു',
    loan_btn_apply: 'അപേക്ഷിക്കുക',
    bank_national: 'ദേശീയ ബാങ്കുകൾ',
    bank_state_specific: 'സംസ്ഥാന സഹകരണ ബാങ്കുകൾ',
    bank_sbi: 'സ്റ്റേറ്റ് ബാങ്ക് ഓഫ് ഇന്ത്യ (കൃഷി)',
    bank_nabard: 'നബാർഡ് സഹായം',
    bank_hdfc: 'എച്ച്.ഡി.എഫ്.സി ബാങ്ക് അഗ്രി ലോൺ',
    bank_kerala: 'കേരള ബാങ്ക്',
    bank_tnscb: 'തമിഴ്‌നാട് സ്റ്റേറ്റ് കോ-ഓപ്പറേറ്റീവ് ബാങ്ക്',
    btn_apply_bank: 'ബാങ്ക് പോർട്ടലിൽ അപേക്ഷിക്കുക',
    // Community ML
    forum_peer_network: 'കൃഷി പിയർ നെറ്റ്വർക്ക്',
    forum_title: 'ഫോറം',
    forum_btn_post: 'ചോദിക്കുക',
    forum_label_crop: 'പ്രധാന കൃഷി',
    forum_label_category: 'വിഭാഗം',
    forum_label_district: 'ജില്ല',
    forum_label_inquiry: 'വിശദാംശങ്ങൾ',
    forum_btn_submit: 'സബ്മിറ്റ് ചെയ്യുക',
    forum_suggestions_title: 'മറ്റ് കർഷകരുടെ നിർദ്ദേശങ്ങൾ',
    forum_reply_placeholder: 'നിങ്ങളുടെ നിർദ്ദേശം എഴുതുക...',
    live_sync_title: 'കൃഷി സിങ്ക്.',
    live_latency: 'വേഗത',
    live_latency_val: 'തത്സമയം (~200ms)',
    live_engine: 'കോർ എൻജിൻ',
    live_engine_val: 'ജെമിനി 2.5 നേറ്റീവ്',
    live_advisory_mode: 'വോയ്‌സ് മോഡ്',
    live_dialect_val: 'മലയാളം ഡയലക്ട്',
    live_listening: 'ശ്രദ്ധിക്കുന്നു...',
    live_idle: 'സിസ്റ്റം വിശ്രമത്തിൽ',
    live_connecting: 'ബന്ധിപ്പിക്കുന്നു...',
    live_you: 'നിങ്ങൾ',
    live_subtitle: 'തത്സമയ കാർഷിക പിന്തുണയ്ക്കായി വോയ്‌സ് സംഭാഷണം.',
    live_btn_end: 'അവസാനിപ്പിക്കുക',
    live_btn_start: 'തുടങ്ങുക',
    profile_name_label: 'പേര്',
    profile_age_label: 'വയസ്സ്',
    profile_address_label: 'വിലാസം',
    profile_id_label: 'രജിസ്ട്രി ഐഡി',
    login_title: 'കൃഷി ലോഗിൻ',
    login_subtitle: 'സുരക്ഷിത പ്രവേശനം',
    login_placeholder_phone: 'ഫോൺ ഐഡി',
    login_placeholder_pass: 'പിൻ / പാസ്‌വേഡ്',
    login_btn_enter: 'പ്രവേശിക്കുക',
    login_forgot_pass: 'പാസ്‌വേഡ് മറന്നോ?',
    login_btn_cancel: 'റദ്ദാക്കുക',
    register_title: 'പുതിയ രജിസ്ട്രേഷൻ',
    register_subtitle: 'കൃഷി വോൾട്ട് ആരംഭിക്കുക',
    register_btn_secure: 'തുടരുക',
    footer_desc: 'AI അധിഷ്ഠിത വിവരങ്ങളിലൂടെ കർഷകരെ ശാക്തീകരിക്കുന്നു.',
    footer_quick_links: 'ലിങ്കുകൾ',
    footer_contact_support: 'സഹായം',
    onboarding_step: 'ഘട്ടം',
    onboarding_completed: 'പൂർത്തിയായി',
    onboarding_identity_sync: 'ഐഡന്റിറ്റി സിങ്ക്',
    onboarding_start_digital_record: 'നിങ്ങളുടെ ഡിജിറ്റൽ റെക്കോർഡ് ആരംഭിക്കുക',
    onboarding_full_name: 'പൂർണ്ണനാമം',
    onboarding_example_name: 'ഉദാഹരണം: സച്ചിൻ എസ്',
    onboarding_age: 'വയസ്സ്',
    onboarding_experience: 'പരിചയം (വർഷങ്ങൾ)',
    onboarding_farm_address: 'ഫാം വിലാസം',
    onboarding_address_placeholder: 'ഗ്രാമം, ജില്ല, സംസ്ഥാനം...',
    onboarding_btn_location: 'ലൊക്കേഷനിലേക്ക് പോകുക',
    onboarding_geo_center: 'ഭൂമിശാസ്ത്ര കേന്ദ്രം',
    onboarding_sync_weather: 'പ്രാദേശിക കാലാവസ്ഥാ ഡാറ്റയുമായി സമന്വയിപ്പിക്കുക',
    onboarding_state: 'സംസ്ഥാനം',
    onboarding_district: 'ജില്ല',
    onboarding_select: 'തിരഞ്ഞെടുക്കുക...',
    onboarding_btn_back: 'പിന്നിലേക്ക്',
    onboarding_agri_dna_profile: 'കാർഷിക ഡിഎൻഎ പ്രൊഫൈൽ',
    onboarding_agri_dna: 'കാർഷിക ഡിഎൻഎ',
    onboarding_define_genetics: 'നിങ്ങളുടെ മണ്ണും വിള ജനിതകവും നിർവചിക്കുക',
    onboarding_primary_crop_cultivation: 'പ്രാഥമിക വിള കൃഷി',
    onboarding_soil_profile: 'മണ്ണ് ഘടന പ്രൊഫൈൽ',
    onboarding_btn_finalize: 'അളവുകൾ അന്തിമമാക്കുക',
    onboarding_operational_status: 'പ്രവർത്തന നില',
    onboarding_finalizing_management: 'ഭൂമി, വിഭവ മാനേജ്‌മെന്റ് അന്തിമമാക്കുന്നു',
    onboarding_total_land_size: 'ആകെ ഭൂമി (ഏക്കർ)',
    onboarding_acres: 'ഏക്കർ',
    onboarding_irrigation_infrastructure: 'ജലസേചന അടിസ്ഥാന സൗകര്യങ്ങൾ',
    onboarding_btn_start_center: 'കമാൻഡ് സെന്റർ ആരംഭിക്കുക',
    onboarding_protected_badge: 'കിസാൻ ഐഡന്റിറ്റി പ്രോട്ടോക്കോൾ വഴി സംരക്ഷിക്കപ്പെട്ടിരിക്കുന്നു',
    guardian_title: 'ഉഴവൻ സ്മാർട്ട് ഇറിഗേഷൻ ഗാർഡിയൻ',
    guardian_tagline: 'സ്മാർട്ട് കൃഷി ഇവിടെ തുടങ്ങുന്നു',
    guardian_buy_now: 'ഇപ്പോൾ വാങ്ങുക',
    guardian_contact_us: 'ഞങ്ങളെ ബന്ധപ്പെടുക',
    guardian_overview_title: 'ഉൽപ്പന്ന അവലോകനം',
    guardian_overview_desc: 'ഞങ്ങളുടെ AI-അധിഷ്ഠിത IoT സിസ്റ്റം ആധുനിക കൃഷിക്ക് സമഗ്രമായ നിരീക്ഷണവും നിയന്ത്രണവും നൽകുന്നു.',
    guardian_soil_moisture: 'മണ്ണിലെ ഈർപ്പം നിരീക്ഷിക്കൽ',
    guardian_temp_humidity: 'താപനിലയും ഈർപ്പവും',
    guardian_auto_motor: 'ഓട്ടോമാറ്റിക് മോട്ടോർ നിയന്ത്രണം',
    guardian_wifi_realtime: 'വൈഫൈ അടിസ്ഥാനമാക്കിയുള്ള തത്സമയ നിരീക്ഷണം',
    guardian_solar_support: 'സൗരോർജ്ജ പിന്തുണ',
    guardian_features_title: 'നൂതന സവിശേഷതകൾ',
    guardian_feature_soil: 'തത്സമയ മണ്ണ് നിരീക്ഷണം',
    guardian_feature_irrigation: 'സ്മാർട്ട് ജലസേചന നിയന്ത്രണം',
    guardian_feature_dashboard: 'വൈഫൈ വെബ് ഡാഷ്‌ബോർഡ്',
    guardian_feature_mobile: 'മൊബൈൽ ആക്സസ്',
    guardian_feature_energy: 'ഊർജ്ജ കാര്യക്ഷമത',
    guardian_feature_install: 'എളുപ്പത്തിലുള്ള ഇൻസ്റ്റാളേഷൻ',
    guardian_how_it_works: 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
    guardian_step_1: 'വയലിൽ ഉപകരണം സ്ഥാപിക്കുക',
    guardian_step_2: 'സെൻസറുകൾ തത്സമയ ഡാറ്റ ശേഖരിക്കുന്നു',
    guardian_step_3: 'ESP32 ഡാറ്റ പ്രോസസ്സ് ചെയ്യുന്നു',
    guardian_step_4: 'മോട്ടോർ ഓട്ടോമാറ്റിക്കായി ജലസേചനം നിയന്ത്രിക്കുന്നു',
    guardian_step_5: 'കർഷകൻ വെബ് ഡാഷ്‌ബോർഡ് വഴി നിരീക്ഷിക്കുന്നു',
    guardian_tech_specs: 'സാങ്കേതിക സവിശേഷതകൾ',
    guardian_spec_mcu: 'മൈക്രോകൺട്രോളർ: ESP32',
    guardian_spec_soil: 'സോയിൽ സെൻസർ: കപ്പാസിറ്റീവ് സോയിൽ മോയിസ്ചർ സെൻസർ',
    guardian_spec_env: 'എൻവയോൺമെന്റൽ സെൻസർ: DHT11/DHT22',
    guardian_spec_power: 'പവർ സപ്ലൈ: 5V / സോളാർ കോംപാറ്റിബിൾ',
    guardian_spec_wifi: 'കണക്റ്റിവിറ്റി: വൈഫൈ 2.4 GHz',
    guardian_spec_relay: 'റിലേ മോഡ്യൂൾ: 5V ആക്റ്റീവ് ലോ',
    guardian_benefits: 'ഗുണങ്ങൾ',
    guardian_benefit_water: 'വെള്ളം ലാഭിക്കുന്നു',
    guardian_benefit_yield: 'വിളവ് വർദ്ധിപ്പിക്കുന്നു',
    guardian_benefit_effort: 'അധ്വാനം കുറയ്ക്കുന്നു',
    guardian_benefit_stress: 'നേരത്തെയുള്ള സ്ട്രെസ് ഡിറ്റക്ഷൻ',
    guardian_benefit_cost: 'ചെലവ് കുറഞ്ഞത്',
    guardian_gallery: 'ചിത്രശാല',
    guardian_pricing: 'വില വിവരങ്ങൾ',
    guardian_basic: 'ബേസിക് മോഡൽ',
    guardian_pro: 'പ്രോ മോഡൽ',
    guardian_enterprise: 'എന്റർപ്രൈസ് മോഡൽ',
    guardian_cta: 'ഇന്ന് തന്നെ നിങ്ങളുടെ ഫാം അപ്‌ഗ്രേഡ് ചെയ്യൂ!',
    // Store ML
    store_title: 'ഉഴവൻ സ്റ്റോർ',
    store_badge: 'കർഷക വിപണി',
    store_subtitle: 'നിങ്ങളുടെ കൃഷിക്ക് ആവശ്യമായ മികച്ച ഉൽപ്പന്നങ്ങൾ.',
    store_add_cart: 'കൂടയിൽ ചേർക്കുക',
    cat_all: 'എല്ലാം',
    cat_fertilizer: 'വളം',
    cat_pesticide: 'കീടനാശിനി',
    cat_seeds: 'വിത്ത്',
    cat_tools: 'കൃഷി ഉപകരണങ്ങൾ',
    p1_name: 'വേപ്പ് എണ്ണ കീടനാശിനി',
    p1_desc: 'ജൈവ വേപ്പ് എണ്ണ കോൺസൺട്രേറ്റ്. മൂട്ട, ഇലപ്പേൻ, കൂൺ രോഗങ്ങൾ നിയന്ത്രിക്കാൻ ഫലപ്രദം.',
    p2_name: 'NPK 19:19:19 വളം',
    p2_desc: 'സമതുലിത ജലത്തിൽ ലയിക്കുന്ന NPK വളം. വേര്, കാണ്ഡം, ഫലം എന്നിവ ആരോഗ്യകരമായി വളർത്തുന്നു.',
    p3_name: 'ഹൈബ്രിഡ് നെൽ വിത്ത്',
    p3_desc: 'ഉയർന്ന ഉൽപ്പാദനക്ഷമതയുള്ള ഹൈബ്രിഡ് നെൽ വിത്ത്. 120 ദിവസം ദൈർഘ്യം, കീടപ്രതിരോധ ശേഷി.',
    p4_name: 'കോപ്പർ ഓക്‌സി ക്ലോറൈഡ് ഫംഗിസൈഡ്',
    p4_desc: 'ഇലകൾ, നെല്ല്, പച്ചക്കറി എന്നിവയിലെ ദ്രവ ആക്രമണം, ഇലക്കരിച്ചിൽ നിയന്ത്രിക്കുന്ന ഫംഗിസൈഡ്.',
    p5_name: 'വേർമി കമ്പോസ്റ്റ് ജൈവ വളം',
    p5_desc: 'മണ്ണിര ഉപയോഗിച്ച് ഉണ്ടാക്കിയ ഉന്നതഗുണ ജൈവ കമ്പോസ്റ്റ്. മണ്ണിന്റെ ഗുണം വർദ്ധിപ്പിക്കുന്നു.',
    p6_name: 'സ്റ്റൈൻലെസ് സ്റ്റീൽ അരിവാൾ',
    p6_desc: 'കൂർത്ത കറ്റ്-ബ്ലേഡുള്ള പരമ്പരാഗത അരിവാൾ. നെൽ, ഗോതമ്പ്, പുല്ല് കൊയ്ത്തിന് ഉത്തമം.',
    p7_name: 'ഇരുമ്പ് കൊത്തുമ്പ്',
    p7_desc: 'ശക്തമായ ഇരുമ്പ് കൊത്തുമ്പ്, ആർഗണൊമിക് കൈപ്പിടി. കളനാശനം, മണ്ണ് ഇളക്കൽ, ബെഡ് തയ്യാറാക്കൽ.',
    p8_name: 'തെങ്ങ് കയറ്റ ഉപകരണ കിറ്റ്',
    p8_desc: 'സുരക്ഷിതവും ഈടുനിൽക്കുന്നതുമായ തെങ്ങ് കയറ്റ സഹായ ഉപകരണം. 120 കി.ഗ്രാം ഭാരം താങ്ങുന്നു.',
    p9_name: 'പച്ചക്കറി വിത്ത് കോംബോ പാക്ക്',
    p9_desc: '10 തരം പച്ചക്കറി വിത്തുകൾ — കത്തിരി, തക്കാളി, മുളക്, ഉരുളക്കിഴങ്ങ്, കയ്പക്ക തുടങ്ങിയവ.',
    p10_name: 'DAP ഫോസ്ഫേറ്റ് വളം (50 കി.ഗ്രാം)',
    p10_desc: 'ഡൈ-അമോണിയം ഫോസ്ഫേറ്റ്. വേര് ബലപ്പെടുത്തലിനും ആദ്യകാല കൃഷി സ്ഥാപനത്തിനും അത്യാവശ്യം.'
  },
  Tamil: {
    nav_home: 'முகப்பு',
    nav_query: 'AI கேள்வி',
    nav_live: 'குரல் ஆலோசனை',
    nav_community: 'கூட்டமைப்பு',
    nav_schemes: 'அரசு திட்டங்கள்',
    nav_profile: 'எனது சுயவிவரம்',
    nav_dashboard: 'அதிகாரி டாஷ்போர்டு',
    nav_tech: 'தொழில்நுட்ப விவரங்கள்',
    nav_logout: 'வெளியேறு',
    nav_store: 'உழவன் ஸ்டோர்',
    nav_weather: 'வானிலை மையம்',
    nav_loans: 'வங்கி கடன்கள்',
    nav_guardian: 'பாதுகாவலர்',
    nav_elam: '🌾 ஏலம்',
    nav_search_placeholder: 'தேடுங்கள்...',
    nav_farmer_role: 'விவசாயி',
    hero_title_1: 'உழவன்',
    hero_title_2: 'மன்றம்.',
    hero_subtitle: "தனிப்பயனாக்கப்பட்ட நுண்ணறிவுடன் பாரதத்தின் விவசாயத்தை மறுவரையறை செய்தல்.",
    btn_login: 'உள்நுழைவு',
    btn_strategy: 'உத்தி',
    home_ai_center: 'AI விவசாய கட்டளை மையம்',
    query_title: 'விவசாயி ஆலோசனை மையம்',
    query_diagnostic_title: 'AI கண்டறியும் கேள்வி',
    query_btn_ask: 'AI ஆலோசனை மூலம் சரிபார்க்கவும்',
    query_analyzing: 'தரவை பகுப்பாய்வு செய்கிறது...',
    query_report_title: 'ஆலோசனை அறிக்கை',
    query_voice_start: 'அறிக்கையைக் கேளுங்கள்',
    query_voice_stop: 'குரலை நிறுத்து',
    query_system_status: 'கணினி நிலை',
    query_grounding: 'தரைவழி நிலை',
    query_optimal: 'சிறந்தது',
    query_voice_ready: 'தயார்',
    query_model_series: 'மாதிரித் தொடர்',
    query_verified_title: 'சரிபார்க்கப்பட்ட அறிக்கை',
    query_verified_desc: 'எங்கள் AI செயற்கைக்கோள் தரவைப் பயன்படுத்தி உங்கள் பயிர் சிக்கல்களைச் சரிபார்க்கிறது.',
    query_capture_mandatory: 'படத்தை பதிவேற்றவும் அல்லது கேள்வியை தட்டச்சு செய்யவும்',
    onboarding_title: 'சுயவிவரத்தை நிறைவு செய்தல்',
    onboarding_choose: 'தேர்ந்தெடு...',
    onboarding_btn_next: 'தொடரவும்',
    onboarding_btn_complete: 'நிறைவு செய்',
    onboarding_label_land: 'நில அளவு (ஏக்கர்)',
    crop_paddy: 'நெல்',
    crop_rubber: 'ரப்பர்',
    crop_coconut: 'தென்னை',
    crop_pepper: 'மிளகு',
    crop_banana: 'வாழை',
    crop_coffee: 'காபி',
    crop_arecanut: 'பாக்கு',
    crop_cardamom: 'ஏலக்காய்',
    crop_vegetables: 'காய்கறிகள்',
    crop_ginger: 'இஞ்சி',
    crop_turmeric: 'மஞ்சள்',
    soil_black: 'கரிசல் மண்',
    soil_red: 'செம்மண்',
    soil_alluvial: 'வண்டல் மண்',
    soil_laterite: 'சரளை மண்',
    soil_sandy: 'மணல் மண்',
    soil_clay: 'களிமண்',
    irr_drip: 'சொட்டு நீர் பாசனம்',
    irr_sprinkler: 'தெளிப்பு நீர் பாசனம்',
    irr_canal: 'கால்வாய் பாசனம்',
    irr_well: 'கிணறு',
    irr_rain: 'மழைநீர் ஆதாரம்',
    weather_title: 'வானிலை மையம்',
    weather_feed_title: 'நேரடி வானிலை மையம்.',
    weather_recent: 'சமீபத்திய இடங்கள்',
    weather_scanning: 'வானிலை ஆய்வு செய்கிறது...',
    weather_system_suitability_ai: 'விவசாய பொருத்தம் AI',
    weather_verify_now: 'சரிபார்க்கவும்',
    weather_weekly: 'வாராந்திர முன்னறிவிப்பு',
    weather_advisory_title: 'AI ஆலோசனை',
    weather_log: 'விவசாய வரலாறு',
    weather_spec: 'விவரக்குறிப்பு',
    weather_verdict: 'AI தீர்ப்பு',
    weather_matrix: 'அறிவியல் தரவு',
    weather_logic: 'ஆலோசனை தர்க்கம்',
    weather_hear_analysis: 'பகுப்பாய்வைக் கேளுங்கள்',
    weather_km_h: 'கி.மீ/மணி',
    weather_humidity: 'ஈரப்பதம்',
    weather_btn_fetch: 'தரவைப் பெறு',
    wmo_0: 'தெளிவான வானம்',
    wmo_1: 'பெரும்பாலும் தெளிவாக உள்ளது',
    wmo_2: 'பகுதியளவு மேகமூட்டம்',
    wmo_3: 'மேகமூட்டம்',
    wmo_45: 'மூடுபனி',
    wmo_48: 'அடர்த்தியான மூடுபனி',
    wmo_51: 'லேசான தூறல்',
    wmo_53: 'மிதமான தூறல்',
    wmo_55: 'அடர்த்தியான தூறல்',
    wmo_61: 'லேசான மழை',
    wmo_63: 'மிதமான மழை',
    wmo_65: 'கனமழை',
    wmo_80: 'மழைத் துளிகள்',
    wmo_81: 'மிதமான மழைத் துளிகள்',
    wmo_82: 'பலத்த மழைத் துளிகள்',
    wmo_95: 'இடியுடன் கூடிய மழை',
    // Schemes TA
    schemes_title: 'அரசு திட்டங்கள்',
    schemes_discovery: 'கண்டறிதல்',
    schemes_subtitle: '2026 வரை செயலில் உள்ள மத்திய மற்றும் மாநில விவசாய சலுகைகளை அணுகவும்.',
    schemes_central: 'மத்திய அரசு',
    schemes_state: 'மாநில அரசு',
    schemes_verified: 'சரிபார்க்கப்பட்டது 2026',
    schemes_proceed_portal: 'போர்ட்டலுக்குச் செல்லவும்',
    scheme_pmkisan_name: 'PM-KISAN (வருமான ஆதரவு)',
    scheme_pmkisan_desc: 'விவசாய குடும்பங்களுக்கு ஆண்டுக்கு ₹6,000 வருமான ஆதரவு.',
    scheme_pmfby_name: 'PMFBY (பயிர் காப்பீடு)',
    scheme_pmfby_desc: 'இயற்கை இடர்பாடுகளுக்கு எதிரான பயிர் காப்பீடு.',
    scheme_kcc_name: 'கிசான் கிரெடிட் கார்டு (KCC)',
    scheme_kcc_desc: 'பயிர் உற்பத்தி மற்றும் பராமரிப்புக்கான கடன் உதவித் திட்டம்.',
    scheme_shc_name: 'மண் வள அட்டைத் திட்டம்',
    scheme_shc_desc: 'மண்ணின் ஆரோக்கியத்தை ஆய்வு செய்து உரப்பரிந்துரை வழங்கும் திட்டம்.',
    scheme_pkvy_name: 'பரம்பராகத் கிரிஷி விகாஸ் யோஜனா',
    scheme_pkvy_desc: 'இயற்கை விவசாயத்தை ஊக்குவிக்கும் திட்டம்.',
    scheme_nmsa_name: 'நிலையான விவசாயத்திற்கான இயக்கம்',
    scheme_nmsa_desc: 'ஒருங்கிணைந்த பண்ணை முறை மூலம் உற்பத்தித் திறனை அதிகரித்தல்.',
    scheme_pmksy_name: 'PM கிரிஷி சிஞ்சாயி யோஜனா',
    scheme_pmksy_desc: 'பாசன வசதிகளை மேம்படுத்தும் திட்டம்.',
    // Loan Hub TA
    loan_hub_title: 'கடன் மையம்',
    loan_hub_subtitle: 'சந்தை தரவுகளின் அடிப்படையில் விவசாய கடன் கண்டறிதல்.',
    loan_applied: 'விண்ணப்பிக்கப்பட்டது',
    loan_btn_apply: 'விண்ணப்பிக்கவும்',
    bank_national: 'தேசிய வங்கிகள்',
    bank_state_specific: 'மாநில கூட்டுறவு வங்கிகள்',
    bank_sbi: 'பாரத ஸ்டேட் வங்கி (விவசாயம்)',
    bank_nabard: 'நபார்டு வங்கி உதவி',
    bank_hdfc: 'HDFC வங்கி விவசாய கடன்',
    bank_kerala: 'கேரளா பேங்க்',
    bank_tnscb: 'தமிழ்நாடு மாநில கூட்டுறவு வங்கி',
    btn_apply_bank: 'வங்கி போர்ட்டலில் விண்ணப்பிக்கவும்',
    // Community TA
    forum_peer_network: 'உழவன் நெட்வொர்க்',
    forum_title: 'சமூக மன்றம்',
    forum_btn_post: 'கேள்வி கேட்க',
    forum_label_crop: 'முதன்மை பயிர்',
    forum_label_category: 'வகை',
    forum_label_district: 'மாவட்டம்',
    forum_label_inquiry: 'விவரமான விசாரணை',
    forum_btn_submit: 'சமர்ப்பிக்கவும்',
    forum_suggestions_title: 'விவசாயிகளின் ஆலோசனைகள்',
    forum_reply_placeholder: 'உங்கள் ஆலோசனையை தட்டச்சு செய்க...',
    live_sync_title: 'கிரிஷி சிங்க்.',
    live_latency: 'தாமதம்',
    live_latency_val: 'நிகழ்நேரம் (~200ms)',
    live_engine: 'முக்கிய எஞ்சின்',
    live_engine_val: 'ஜெமினி 2.5 நேட்டிவ்',
    live_advisory_mode: 'குரல் முறை',
    live_dialect_val: 'தமிழ் பேச்சு வழக்கு',
    live_listening: 'கேட்கிறது...',
    live_idle: 'கணினி தயார் நிலையில் உள்ளது',
    live_connecting: 'இணைக்கப் படுகிறது...',
    live_you: 'நீங்கள்',
    live_subtitle: 'உடனடி விவசாய ஆதரவுக்கான நிகழ்நேர குரல் தொடர்பு.',
    live_btn_end: 'முடிவு',
    live_btn_start: 'தொடங்கு',
    profile_name_label: 'முழு பெயர்',
    profile_age_label: 'வயது',
    profile_address_label: 'முகவரி',
    profile_id_label: 'பதிவு எண்',
    login_title: 'உள்நுழைவு',
    login_subtitle: 'பாதுகாப்பான அணுகல்',
    login_placeholder_phone: 'தொலைபேசி எண்',
    login_placeholder_pass: 'கடவுச்சொல்',
    login_btn_enter: 'உள்நுழைக',
    login_forgot_pass: 'கடவுச்சொல்லை மறந்தீர்களா?',
    login_btn_cancel: 'ரத்துசெய்',
    register_title: 'புதிய பதிவு',
    register_subtitle: 'கிரிஷி கணக்கைத் தொடங்கவும்',
    register_btn_secure: 'தொடரவும்',
    footer_desc: 'நிலையான விவசாயத்திற்காக AI மூலம் விவசாயிகளுக்கு சிறந்த ஆலோசனைகளை வழங்குகிறோம்.',
    footer_quick_links: 'விரைவு இணைப்புகள்',
    footer_contact_support: 'ஆதரவு',
    onboarding_step: 'நிலை',
    onboarding_completed: 'முடிந்தது',
    onboarding_identity_sync: 'அடையாள ஒத்திசைவு',
    onboarding_start_digital_record: 'உங்கள் டிஜிட்டல் பதிவேட்டைத் தொடங்கவும்',
    onboarding_full_name: 'முழு பெயர்',
    onboarding_example_name: 'உதாரணம்: சச்சின் எஸ்',
    onboarding_age: 'வயது',
    onboarding_experience: 'அனுபவம் (ஆண்டுகள்)',
    onboarding_farm_address: 'பண்ணை முகவரி',
    onboarding_address_placeholder: 'கிராமம், மாவட்டம், மாநிலம்...',
    onboarding_btn_location: 'இருப்பிடத்திற்குச் செல்லவும்',
    onboarding_geo_center: 'புவியியல் மையம்',
    onboarding_sync_weather: 'உள்ளூர் தட்பவெப்ப நிலைத் தரவுகளுடன் ஒத்திசைக்கவும்',
    onboarding_state: 'மாநிலம்',
    onboarding_district: 'மாவட்டம்',
    onboarding_select: 'தேர்ந்தெடுக்கவும்...',
    onboarding_btn_back: 'பின்னால்',
    onboarding_agri_dna_profile: 'விவசாய டிஎன்ஏ விவரக்குறிப்பு',
    onboarding_agri_dna: 'விவசாய டிஎன்ஏ',
    onboarding_define_genetics: 'உங்கள் மண் மற்றும் பயிர் மரபியலை வரையறுக்கவும்',
    onboarding_primary_crop_cultivation: 'முதன்மை பயிர் சாகுபடி',
    onboarding_soil_profile: 'மண் அமைப்பு விவரக்குறிப்பு',
    onboarding_btn_finalize: 'அளவீடுகளை இறுதி செய்யுங்கள்',
    onboarding_operational_status: 'செயல்பாட்டு நிலை',
    onboarding_finalizing_management: 'நிலம் மற்றும் வள மேலாண்மையை இறுதி செய்கிறது',
    onboarding_total_land_size: 'மொத்த நில அளவு (ஏக்கர்)',
    onboarding_acres: 'ஏக்கர்',
    onboarding_irrigation_infrastructure: 'பாசன உள்கட்டமைப்பு',
    onboarding_btn_start_center: 'கட்டளை மையத்தைத் தொடங்குங்கள்',
    onboarding_protected_badge: 'கிசான் அடையாள நெறிமுறை மூலம் பாதுகாக்கப்பட்டது',
    guardian_title: 'உழவன் ஸ்மார்ட் பாசன பாதுகாவலர்',
    guardian_tagline: 'ஸ்மார்ட் விவசாயம் இங்கே தொடங்குகிறது',
    guardian_buy_now: 'இப்போதே வாங்கவும்',
    guardian_contact_us: 'எங்களைத் தொடர்பு கொள்ளவும்',
    guardian_overview_title: 'தயாரிப்பு கண்ணோட்டம்',
    guardian_overview_desc: 'எங்கள் AI-இயக்கப்பட்ட IoT அமைப்பு நவீன விவசாயத்திற்கு விரிவான கண்காணிப்பு மற்றும் கட்டுப்பாட்டை வழங்குகிறது.',
    guardian_soil_moisture: 'மண் ஈரப்பதம் கண்காணிப்பு',
    guardian_temp_humidity: 'வெப்பநிலை மற்றும் ஈரப்பதம்',
    guardian_auto_motor: 'தானியங்கி மோட்டார் கட்டுப்பாடு',
    guardian_wifi_realtime: 'வைஃபை அடிப்படையிலான நிகழ்நேர கண்காணிப்பு',
    guardian_solar_support: 'சூரிய சக்தி ஆதரவு',
    guardian_features_title: 'மேம்பட்ட அம்சங்கள்',
    guardian_feature_soil: 'நிகழ்நேர மண் கண்காணிப்பு',
    guardian_feature_irrigation: 'ஸ்மார்ட் பாசனக் கட்டுப்பாடு',
    guardian_feature_dashboard: 'வைஃபை வலை டாஷ்போர்டு',
    guardian_feature_mobile: 'மொபைல் அணுகல்',
    guardian_feature_energy: 'ஆற்றல் திறன்',
    guardian_feature_install: 'எளிதான நிறுவல்',
    guardian_how_it_works: 'இது எப்படி வேலை செய்கிறது',
    guardian_step_1: 'வயலில் சாதனத்தை நிறுவவும்',
    guardian_step_2: 'சென்சார்கள் நிகழ்நேரத் தரவைச் சேகரிக்கின்றன',
    guardian_step_3: 'ESP32 தரவைச் செயலாக்குகிறது',
    guardian_step_4: 'மோட்டார் தானாகவே பாசனத்தைக் கட்டுப்படுத்துகிறது',
    guardian_step_5: 'விவசாயி வலை டாஷ்போர்டு மூலம் கண்காணிக்கிறார்',
    guardian_tech_specs: 'தொழில்நுட்ப விவரக்குறிப்புகள்',
    guardian_spec_mcu: 'மைக்ரோகண்ட்ரோலர்: ESP32',
    guardian_spec_soil: 'மண் சென்சார்: கொள்ளளவு மண் ஈரப்பதம் சென்சார்',
    guardian_spec_env: 'சுற்றுச்சூழல் சென்சார்: DHT11/DHT22',
    guardian_spec_power: 'மின்சாரம்: 5V / சூரிய சக்தி இணக்கமானது',
    guardian_spec_wifi: 'இணைப்பு: வைஃபை 2.4 GHz',
    guardian_spec_relay: 'ரிலே தொகுதி: 5V ஆக்டிவ் லோ',
    guardian_benefits: 'நன்மைகள்',
    guardian_benefit_water: 'தண்ணீரைச் சேமிக்கிறது',
    guardian_benefit_yield: 'மகசூலை அதிகரிக்கிறது',
    guardian_benefit_effort: 'மனித முயற்சியைக் குறைக்கிறது',
    guardian_benefit_stress: 'ஆரம்பகால மன அழுத்தத்தைக் கண்டறிதல்',
    guardian_benefit_cost: 'செலவு குறைந்தது',
    guardian_gallery: 'புகைப்பட தொகுப்பு',
    guardian_pricing: 'விலை திட்டங்கள்',
    guardian_basic: 'அடிப்படை மாதிரி',
    guardian_pro: 'புரோ மாதிரி',
    guardian_enterprise: 'எண்டர்பிரைஸ் மாதிரி',
    guardian_cta: 'இன்றே உங்கள் பண்ணையை மேம்படுத்துங்கள்!',
    // Store TA
    store_title: 'உழவன் ஸ்டோர்',
    store_badge: 'விவசாயிகள் சந்தை',
    store_subtitle: 'உங்கள் பண்ணைக்கு தேவையான சிறந்த விவசாய பொருட்கள்.',
    store_add_cart: 'கூடையில் சேர்',
    cat_all: 'அனைத்தும்',
    cat_fertilizer: 'உரம்',
    cat_pesticide: 'பூச்சிக்கொல்லி',
    cat_seeds: 'விதைகள்',
    cat_tools: 'விவசாய கருவிகள்',
    p1_name: 'வேப்ப எண்ணெய் பூச்சிக்கொல்லி',
    p1_desc: 'இயற்கை குளிர்-அழுத்தம் வேப்ப எண்ணெய் கலவை. அசுவினி, பூஞ்சை தொற்றுகளுக்கு மிகவும் பயனுள்ளது.',
    p2_name: 'NPK 19:19:19 உரம்',
    p2_desc: 'சம அளவு தண்ணீரில் கரையக்கூடிய NPK உரம். வேர், தண்டு மற்றும் பழ வளர்ச்சியை ஊக்குவிக்கிறது.',
    p3_name: 'கலப்பின நெல் விதைகள்',
    p3_desc: 'தமிழ்நாடு மற்றும் கேரள தட்பவெப்பத்திற்கு ஏற்ற அதிக மகசூல் தரும் கலப்பின நெல் விதை. 120 நாள் பயிர்.',
    p4_name: 'காப்பர் ஆக்ஸிகுளோரைடு பூஞ்சைக்கொல்லி',
    p4_desc: 'காய்கறி மற்றும் நெல்லில் இலை புள்ளி, குலை கருகல் நோய்களை கட்டுப்படுத்தும் பரவலான பூஞ்சைக்கொல்லி.',
    p5_name: 'மண்புழு உரம் (Vermicompost)',
    p5_desc: 'மண்புழு மூலம் தயாரிக்கப்பட்ட சிறந்த இயற்கை உரம். மண் வளம், நீர் தேக்கம் மற்றும் பயிர் தரம் மேம்படும்.',
    p6_name: 'துருப்பிடிக்காத இரும்பு அரிவாள்',
    p6_desc: 'கூர்மையான இரும்பு அரிவாள். நெல், கோதுமை மற்றும் புல் அறுவடைக்கு சிறந்தது.',
    p7_name: 'இரும்பு குடால் (Hoe)',
    p7_desc: 'வலுவான இரும்பு குடால், வசதியான கைப்பிடி. களை எடுக்க, மண் தோண்ட, படுக்கை தயாரிக்க ஏற்றது.',
    p8_name: 'தென்னை ஏறும் கருவி கிட்',
    p8_desc: 'பாதுகாப்பான தென்னை மரம் ஏறும் கருவி. வழுக்காத பட்டைகளுடன் 120 கிலோ எடையை தாங்கும்.',
    p9_name: 'காய்கறி விதை கலவை பொட்டலம்',
    p9_desc: '10 வகை காய்கறி விதைகள் — கத்தரி, தக்காளி, மிளகாய், அவரை, பாவக்காய் மற்றும் பலவகை விதைகள்.',
    p10_name: 'DAP பாஸ்பேட் உரம் (50 கி.கி பை)',
    p10_desc: 'டை-அமோனியம் பாஸ்பேட் (DAP) கட்டி உரம். வேர் வலுவாக்க மற்றும் ஆரம்பகால பயிர் நிறுவலுக்கு அவசியம்.'
  }
};

export const LanguageProvider: React.FC<{ children?: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('user_language');
    return (saved as Language) || 'English';
  });

  useEffect(() => {
    localStorage.setItem('user_language', language);
    document.documentElement.lang = language === 'English' ? 'en' : language === 'Tamil' ? 'ta' : 'ml';
  }, [language]);

  const t = (key: string) => {
    const dict = translations[language];
    return dict[key] || translations['English'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
